version: '3.8'

services:
    web:
        container_name: django_react
        build: .
        command: python /home/alassane/django_react/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home/alassane/django_react/
        ports:
            - 8000:8000
    db:
        image: postgres:12.8
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRS_HOST_AUTH_METHOD=trust"
            - "POSTGRES_DB=weblog"
            - "POSTGRES_USER=alassane"
            - "POSTGRES_PASSWORD=7678_gone"
            - "POSTGRES_HOST=db"
volumes:
    postgres_data:
