# Generated by Django 3.2.7 on 2021-09-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Author name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='titre')),
                ('subtitle', models.CharField(max_length=150, verbose_name='titre')),
                ('content', models.TextField(verbose_name='content')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('author', models.ManyToManyField(related_name='related_name', to='weblog.Author', verbose_name='author')),
                ('categories', models.ManyToManyField(to='weblog.Category', verbose_name='categories')),
            ],
        ),
    ]
