# Generated by Django 3.2.7 on 2021-10-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_rename_category_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'auteur"),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(related_name='related_name', to='weblog.Author', verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=150, verbose_name='sous-titre'),
        ),
    ]
